
TYPE
	TRAFFIC_LIGHT : 
		(
		TRAFFIC_LIGHT1_RED,
		TRAFFIC_LIGHT2_RED,
		TRAFFIC_LIGHT1_REDYELLOW,
		TRAFFIC_LIGHT2_REDYELLOW,
		TRAFFIC_LIGHT1_YELLOW,
		TRAFFIC_LIGHT2_YELLOW,
		TRAFFIC_LIGHT1_GREEN,
		TRAFFIC_LIGHT2_GREEN
		);
END_TYPE
