
{REDUND_ERROR} FUNCTION_BLOCK STATE_MACHINE (*TODO: Add your comment here*) (*$GROUP=User,$CAT=User,$GROUPICON=User.png,$CATICON=User.png*)
	VAR_INPUT
		EN : BOOL;
		NS : BOOL;
	END_VAR
	VAR_OUTPUT
		Q : STATES;
		ERR : BOOL;
	END_VAR
END_FUNCTION_BLOCK
